#! usr/bin/python -tt

"""
	final version of our implementation
"""

import sys
from pybrain.tools.shortcuts import buildNetwork
from pybrain.datasets.supervised import SupervisedDataSet
from pybrain.supervised.trainers import BackpropTrainer
from pybrain.tools.customxml.networkwriter import NetworkWriter
from pybrain.tools.customxml.networkreader import NetworkReader
import cv2, Image

# function for finding an image
# finds the image and flattens it to a 1d array
def loadImage(path):
	image = cv2.imread(path)
	return convert_to_1d(image)

# collect the pixel data for an image in a 1d array
def convert_to_1d(image):
	result = []
	for element in image:
		if hasattr(element, "__iter__") and not isinstance(element, basestring):
			result.extend(convert_to_1d(element))
		else:
			result.append(element)
	return result

if __name__ == "__main__":

	# use this for determining input size and for building the network
	test_image = loadImage("a/0.png")

	# create the network and training set
	network = buildNetwork(len(test_image), len(test_image), 1)
	training_data = SupervisedDataSet(len(test_image),1)

	# add training images to the training data set, number represents position in the alphabet and desired return value

	# lower case a
	training_data.addSample(loadImage("a/0.png"),(1,))
	training_data.addSample(loadImage("a/1.png"),(1,))
	training_data.addSample(loadImage("a/2.png"),(1,))
	training_data.addSample(loadImage("a/3.png"),(1,))
	training_data.addSample(loadImage("a/4.png"),(1,))
	training_data.addSample(loadImage("a/5.png"),(1,))
	training_data.addSample(loadImage("a/6.png"),(1,))
	training_data.addSample(loadImage("a/7.png"),(1,))
	training_data.addSample(loadImage("a/8.png"),(1,))
	training_data.addSample(loadImage("a/9.png"),(1,))
	training_data.addSample(loadImage("a/10.png"),(1,))
	training_data.addSample(loadImage("a/11.png"),(1,))
	training_data.addSample(loadImage("a/12.png"),(1,))
	training_data.addSample(loadImage("a/13.png"),(1,))
	training_data.addSample(loadImage("a/14.png"),(1,))
	training_data.addSample(loadImage("a/15.png"),(1,))
	training_data.addSample(loadImage("a/16.png"),(1,))
	training_data.addSample(loadImage("a/17.png"),(1,))
	training_data.addSample(loadImage("a/18.png"),(1,))
	training_data.addSample(loadImage("a/19.png"),(1,))
	training_data.addSample(loadImage("a/20.png"),(1,))
	training_data.addSample(loadImage("a/21.png"),(1,))
	training_data.addSample(loadImage("a/22.png"),(1,))
	training_data.addSample(loadImage("a/23.png"),(1,))
	training_data.addSample(loadImage("a/24.png"),(1,))

	# lower case b
	training_data.addSample(loadImage("b/0.png"),(2,))
	training_data.addSample(loadImage("b/1.png"),(2,))
	training_data.addSample(loadImage("b/2.png"),(2,))
	training_data.addSample(loadImage("b/3.png"),(2,))
	training_data.addSample(loadImage("b/4.png"),(2,))
	training_data.addSample(loadImage("b/5.png"),(2,))
	training_data.addSample(loadImage("b/6.png"),(2,))
	training_data.addSample(loadImage("b/7.png"),(2,))
	training_data.addSample(loadImage("b/8.png"),(2,))
	training_data.addSample(loadImage("b/9.png"),(2,))
	training_data.addSample(loadImage("b/10.png"),(2,))
	training_data.addSample(loadImage("b/11.png"),(2,))
	training_data.addSample(loadImage("b/12.png"),(2,))
	training_data.addSample(loadImage("b/13.png"),(2,))
	training_data.addSample(loadImage("b/14.png"),(2,))
	training_data.addSample(loadImage("b/15.png"),(2,))
	training_data.addSample(loadImage("b/16.png"),(2,))
	training_data.addSample(loadImage("b/17.png"),(2,))
	training_data.addSample(loadImage("b/18.png"),(2,))
	training_data.addSample(loadImage("b/19.png"),(2,))
	training_data.addSample(loadImage("b/20.png"),(2,))
	training_data.addSample(loadImage("b/21.png"),(2,))
	training_data.addSample(loadImage("b/22.png"),(2,))
	training_data.addSample(loadImage("b/23.png"),(2,))
	training_data.addSample(loadImage("b/24.png"),(2,))

	# lower case c
	training_data.addSample(loadImage("c/0.png"),(3,))
	training_data.addSample(loadImage("c/1.png"),(3,))
	training_data.addSample(loadImage("c/2.png"),(3,))
	training_data.addSample(loadImage("c/3.png"),(3,))
	training_data.addSample(loadImage("c/4.png"),(3,))
	training_data.addSample(loadImage("c/5.png"),(3,))
	training_data.addSample(loadImage("c/6.png"),(3,))
	training_data.addSample(loadImage("c/7.png"),(3,))
	training_data.addSample(loadImage("c/8.png"),(3,))
	training_data.addSample(loadImage("c/9.png"),(3,))
	training_data.addSample(loadImage("c/10.png"),(3,))
	training_data.addSample(loadImage("c/11.png"),(3,))
	training_data.addSample(loadImage("c/12.png"),(3,))
	training_data.addSample(loadImage("c/13.png"),(3,))
	training_data.addSample(loadImage("c/14.png"),(3,))
	training_data.addSample(loadImage("c/15.png"),(3,))
	training_data.addSample(loadImage("c/16.png"),(3,))
	training_data.addSample(loadImage("c/17.png"),(3,))
	training_data.addSample(loadImage("c/18.png"),(3,))
	training_data.addSample(loadImage("c/19.png"),(3,))
	training_data.addSample(loadImage("c/20.png"),(3,))
	training_data.addSample(loadImage("c/21.png"),(3,))
	training_data.addSample(loadImage("c/22.png"),(3,))
	training_data.addSample(loadImage("c/23.png"),(3,))
	training_data.addSample(loadImage("c/24.png"),(3,))

	# lower case d
	training_data.addSample(loadImage("d/0.png"),(4,))
	training_data.addSample(loadImage("d/1.png"),(4,))
	training_data.addSample(loadImage("d/2.png"),(4,))
	training_data.addSample(loadImage("d/3.png"),(4,))
	training_data.addSample(loadImage("d/4.png"),(4,))
	training_data.addSample(loadImage("d/5.png"),(4,))
	training_data.addSample(loadImage("d/6.png"),(4,))
	training_data.addSample(loadImage("d/7.png"),(4,))
	training_data.addSample(loadImage("d/8.png"),(4,))
	training_data.addSample(loadImage("d/9.png"),(4,))
	training_data.addSample(loadImage("d/10.png"),(4,))
	training_data.addSample(loadImage("d/11.png"),(4,))
	training_data.addSample(loadImage("d/12.png"),(4,))
	training_data.addSample(loadImage("d/13.png"),(4,))
	training_data.addSample(loadImage("d/14.png"),(4,))
	training_data.addSample(loadImage("d/15.png"),(4,))
	training_data.addSample(loadImage("d/16.png"),(4,))
	training_data.addSample(loadImage("d/17.png"),(4,))
	training_data.addSample(loadImage("d/18.png"),(4,))
	training_data.addSample(loadImage("d/19.png"),(4,))
	training_data.addSample(loadImage("d/20.png"),(4,))
	training_data.addSample(loadImage("d/21.png"),(4,))
	training_data.addSample(loadImage("d/22.png"),(4,))
	training_data.addSample(loadImage("d/23.png"),(4,))
	training_data.addSample(loadImage("d/24.png"),(4,))

	# lower case e
	training_data.addSample(loadImage("e/0.png"),(5,))
	training_data.addSample(loadImage("e/1.png"),(5,))
	training_data.addSample(loadImage("e/2.png"),(5,))
	training_data.addSample(loadImage("e/3.png"),(5,))
	training_data.addSample(loadImage("e/4.png"),(5,))
	training_data.addSample(loadImage("e/5.png"),(5,))
	training_data.addSample(loadImage("e/6.png"),(5,))
	training_data.addSample(loadImage("e/7.png"),(5,))
	training_data.addSample(loadImage("e/8.png"),(5,))
	training_data.addSample(loadImage("e/9.png"),(5,))
	training_data.addSample(loadImage("e/10.png"),(5,))
	training_data.addSample(loadImage("e/11.png"),(5,))
	training_data.addSample(loadImage("e/12.png"),(5,))
	training_data.addSample(loadImage("e/13.png"),(5,))
	training_data.addSample(loadImage("e/14.png"),(5,))
	training_data.addSample(loadImage("e/15.png"),(5,))
	training_data.addSample(loadImage("e/16.png"),(5,))
	training_data.addSample(loadImage("e/17.png"),(5,))
	training_data.addSample(loadImage("e/18.png"),(5,))
	training_data.addSample(loadImage("e/19.png"),(5,))
	training_data.addSample(loadImage("e/20.png"),(5,))
	training_data.addSample(loadImage("e/21.png"),(5,))
	training_data.addSample(loadImage("e/22.png"),(5,))
	training_data.addSample(loadImage("e/23.png"),(5,))
	training_data.addSample(loadImage("e/24.png"),(5,))

	# lower case f
	training_data.addSample(loadImage("f/44.png"),(6,))
	training_data.addSample(loadImage("f/45.png"),(6,))
	training_data.addSample(loadImage("f/46.png"),(6,))
	training_data.addSample(loadImage("f/47.png"),(6,))
	training_data.addSample(loadImage("f/48.png"),(6,))
	training_data.addSample(loadImage("f/49.png"),(6,))
	training_data.addSample(loadImage("f/50.png"),(6,))
	training_data.addSample(loadImage("f/51.png"),(6,))
	training_data.addSample(loadImage("f/52.png"),(6,))
	training_data.addSample(loadImage("f/53.png"),(6,))
	training_data.addSample(loadImage("f/54.png"),(6,))
	training_data.addSample(loadImage("f/55.png"),(6,))
	training_data.addSample(loadImage("f/56.png"),(6,))
	training_data.addSample(loadImage("f/57.png"),(6,))
	training_data.addSample(loadImage("f/58.png"),(6,))
	training_data.addSample(loadImage("f/59.png"),(6,))
	training_data.addSample(loadImage("f/60.png"),(6,))
	training_data.addSample(loadImage("f/61.png"),(6,))
	training_data.addSample(loadImage("f/62.png"),(6,))
	training_data.addSample(loadImage("f/63.png"),(6,))
	training_data.addSample(loadImage("f/64.png"),(6,))
	training_data.addSample(loadImage("f/65.png"),(6,))
	training_data.addSample(loadImage("f/66.png"),(6,))
	training_data.addSample(loadImage("f/67.png"),(6,))
	training_data.addSample(loadImage("f/68.png"),(6,))

	# lower case g
	training_data.addSample(loadImage("g/0.png"),(7,))
	training_data.addSample(loadImage("g/1.png"),(7,))
	training_data.addSample(loadImage("g/2.png"),(7,))
	training_data.addSample(loadImage("g/3.png"),(7,))
	training_data.addSample(loadImage("g/4.png"),(7,))
	training_data.addSample(loadImage("g/5.png"),(7,))
	training_data.addSample(loadImage("g/6.png"),(7,))
	training_data.addSample(loadImage("g/7.png"),(7,))
	training_data.addSample(loadImage("g/8.png"),(7,))
	training_data.addSample(loadImage("g/9.png"),(7,))
	training_data.addSample(loadImage("g/10.png"),(7,))
	training_data.addSample(loadImage("g/11.png"),(7,))
	training_data.addSample(loadImage("g/12.png"),(7,))
	training_data.addSample(loadImage("g/13.png"),(7,))
	training_data.addSample(loadImage("g/14.png"),(7,))
	training_data.addSample(loadImage("g/15.png"),(7,))
	training_data.addSample(loadImage("g/16.png"),(7,))
	training_data.addSample(loadImage("g/17.png"),(7,))
	training_data.addSample(loadImage("g/18.png"),(7,))
	training_data.addSample(loadImage("g/19.png"),(7,))
	training_data.addSample(loadImage("g/20.png"),(7,))
	training_data.addSample(loadImage("g/21.png"),(7,))
	training_data.addSample(loadImage("g/22.png"),(7,))
	training_data.addSample(loadImage("g/23.png"),(7,))
	training_data.addSample(loadImage("g/24.png"),(7,))

	# lower case h
	training_data.addSample(loadImage("h/0.png"),(8,))
	training_data.addSample(loadImage("h/1.png"),(8,))
	training_data.addSample(loadImage("h/2.png"),(8,))
	training_data.addSample(loadImage("h/3.png"),(8,))
	training_data.addSample(loadImage("h/4.png"),(8,))
	training_data.addSample(loadImage("h/5.png"),(8,))
	training_data.addSample(loadImage("h/6.png"),(8,))
	training_data.addSample(loadImage("h/7.png"),(8,))
	training_data.addSample(loadImage("h/8.png"),(8,))
	training_data.addSample(loadImage("h/9.png"),(8,))
	training_data.addSample(loadImage("h/10.png"),(8,))
	training_data.addSample(loadImage("h/11.png"),(8,))
	training_data.addSample(loadImage("h/12.png"),(8,))
	training_data.addSample(loadImage("h/13.png"),(8,))
	training_data.addSample(loadImage("h/14.png"),(8,))
	training_data.addSample(loadImage("h/15.png"),(8,))
	training_data.addSample(loadImage("h/16.png"),(8,))
	training_data.addSample(loadImage("h/17.png"),(8,))
	training_data.addSample(loadImage("h/18.png"),(8,))
	training_data.addSample(loadImage("h/19.png"),(8,))
	training_data.addSample(loadImage("h/20.png"),(8,))
	training_data.addSample(loadImage("h/21.png"),(8,))
	training_data.addSample(loadImage("h/22.png"),(8,))
	training_data.addSample(loadImage("h/23.png"),(8,))
	training_data.addSample(loadImage("h/24.png"),(8,))

	# lower case i
	training_data.addSample(loadImage("i/0.png"),(9,))
	training_data.addSample(loadImage("i/1.png"),(9,))
	training_data.addSample(loadImage("i/2.png"),(9,))
	training_data.addSample(loadImage("i/3.png"),(9,))
	training_data.addSample(loadImage("i/4.png"),(9,))
	training_data.addSample(loadImage("i/5.png"),(9,))
	training_data.addSample(loadImage("i/6.png"),(9,))
	
	# lower case j
	training_data.addSample(loadImage("j/0.png"),(10,))
	training_data.addSample(loadImage("j/1.png"),(10,))
	training_data.addSample(loadImage("j/2.png"),(10,))
	training_data.addSample(loadImage("j/3.png"),(10,))
	training_data.addSample(loadImage("j/4.png"),(10,))
	training_data.addSample(loadImage("j/5.png"),(10,))
	training_data.addSample(loadImage("j/6.png"),(10,))
	training_data.addSample(loadImage("j/7.png"),(10,))
	training_data.addSample(loadImage("j/8.png"),(10,))
	training_data.addSample(loadImage("j/9.png"),(10,))
	training_data.addSample(loadImage("j/10.png"),(10,))

	# lower case k
	training_data.addSample(loadImage("k/0.png"),(11,))
	training_data.addSample(loadImage("k/1.png"),(11,))
	training_data.addSample(loadImage("k/2.png"),(11,))
	training_data.addSample(loadImage("k/3.png"),(11,))
	training_data.addSample(loadImage("k/4.png"),(11,))
	training_data.addSample(loadImage("k/5.png"),(11,))
	training_data.addSample(loadImage("k/6.png"),(11,))
	training_data.addSample(loadImage("k/7.png"),(11,))
	training_data.addSample(loadImage("k/8.png"),(11,))
	training_data.addSample(loadImage("k/9.png"),(11,))
	training_data.addSample(loadImage("k/10.png"),(11,))
	training_data.addSample(loadImage("k/11.png"),(11,))
	training_data.addSample(loadImage("k/12.png"),(11,))
	training_data.addSample(loadImage("k/13.png"),(11,))
	training_data.addSample(loadImage("k/14.png"),(11,))
	training_data.addSample(loadImage("k/15.png"),(11,))
	training_data.addSample(loadImage("k/16.png"),(11,))
	training_data.addSample(loadImage("k/17.png"),(11,))
	training_data.addSample(loadImage("k/18.png"),(11,))
	training_data.addSample(loadImage("k/19.png"),(11,))
	training_data.addSample(loadImage("k/20.png"),(11,))
	training_data.addSample(loadImage("k/21.png"),(11,))
	training_data.addSample(loadImage("k/22.png"),(11,))
	training_data.addSample(loadImage("k/23.png"),(11,))
	training_data.addSample(loadImage("k/24.png"),(11,))

	# lower case l
	training_data.addSample(loadImage("l/0.png"),(12,))
	training_data.addSample(loadImage("l/1.png"),(12,))
	training_data.addSample(loadImage("l/2.png"),(12,))
	training_data.addSample(loadImage("l/3.png"),(12,))
	training_data.addSample(loadImage("l/4.png"),(12,))
	training_data.addSample(loadImage("l/5.png"),(12,))
	training_data.addSample(loadImage("l/6.png"),(12,))
	training_data.addSample(loadImage("l/7.png"),(12,))
	training_data.addSample(loadImage("l/8.png"),(12,))
	training_data.addSample(loadImage("l/9.png"),(12,))
	training_data.addSample(loadImage("l/10.png"),(12,))
	training_data.addSample(loadImage("l/11.png"),(12,))
	training_data.addSample(loadImage("l/12.png"),(12,))
	training_data.addSample(loadImage("l/13.png"),(12,))
	training_data.addSample(loadImage("l/14.png"),(12,))
	training_data.addSample(loadImage("l/15.png"),(12,))
	training_data.addSample(loadImage("l/16.png"),(12,))
	training_data.addSample(loadImage("l/17.png"),(12,))
	training_data.addSample(loadImage("l/18.png"),(12,))
	training_data.addSample(loadImage("l/19.png"),(12,))
	training_data.addSample(loadImage("l/20.png"),(12,))
	training_data.addSample(loadImage("l/21.png"),(12,))
	training_data.addSample(loadImage("l/22.png"),(12,))
	training_data.addSample(loadImage("l/23.png"),(12,))
	training_data.addSample(loadImage("l/24.png"),(12,))

	# lower case m
	training_data.addSample(loadImage("m/0.png"),(13,))
	training_data.addSample(loadImage("m/1.png"),(13,))
	training_data.addSample(loadImage("m/2.png"),(13,))
	training_data.addSample(loadImage("m/3.png"),(13,))
	training_data.addSample(loadImage("m/4.png"),(13,))
	training_data.addSample(loadImage("m/5.png"),(13,))
	training_data.addSample(loadImage("m/6.png"),(13,))
	training_data.addSample(loadImage("m/7.png"),(13,))
	training_data.addSample(loadImage("m/8.png"),(13,))
	training_data.addSample(loadImage("m/9.png"),(13,))
	training_data.addSample(loadImage("m/10.png"),(13,))
	training_data.addSample(loadImage("m/11.png"),(13,))
	training_data.addSample(loadImage("m/12.png"),(13,))
	training_data.addSample(loadImage("m/13.png"),(13,))
	training_data.addSample(loadImage("m/14.png"),(13,))
	training_data.addSample(loadImage("m/15.png"),(13,))
	training_data.addSample(loadImage("m/16.png"),(13,))
	training_data.addSample(loadImage("m/17.png"),(13,))
	training_data.addSample(loadImage("m/18.png"),(13,))
	training_data.addSample(loadImage("m/19.png"),(13,))
	training_data.addSample(loadImage("m/20.png"),(13,))
	training_data.addSample(loadImage("m/21.png"),(13,))
	training_data.addSample(loadImage("m/22.png"),(13,))
	training_data.addSample(loadImage("m/23.png"),(13,))
	training_data.addSample(loadImage("m/24.png"),(13,))

	# lower case n
	training_data.addSample(loadImage("n/0.png"),(14,))
	training_data.addSample(loadImage("n/1.png"),(14,))
	training_data.addSample(loadImage("n/2.png"),(14,))
	training_data.addSample(loadImage("n/3.png"),(14,))
	training_data.addSample(loadImage("n/4.png"),(14,))
	training_data.addSample(loadImage("n/5.png"),(14,))
	training_data.addSample(loadImage("n/6.png"),(14,))
	training_data.addSample(loadImage("n/7.png"),(14,))
	training_data.addSample(loadImage("n/8.png"),(14,))
	training_data.addSample(loadImage("n/9.png"),(14,))
	training_data.addSample(loadImage("n/10.png"),(14,))
	training_data.addSample(loadImage("n/11.png"),(14,))
	training_data.addSample(loadImage("n/12.png"),(14,))
	training_data.addSample(loadImage("n/13.png"),(14,))
	training_data.addSample(loadImage("n/14.png"),(14,))
	training_data.addSample(loadImage("n/15.png"),(14,))
	training_data.addSample(loadImage("n/16.png"),(14,))
	training_data.addSample(loadImage("n/17.png"),(14,))
	training_data.addSample(loadImage("n/18.png"),(14,))
	training_data.addSample(loadImage("n/19.png"),(14,))
	training_data.addSample(loadImage("n/20.png"),(14,))
	training_data.addSample(loadImage("n/21.png"),(14,))
	training_data.addSample(loadImage("n/22.png"),(14,))
	training_data.addSample(loadImage("n/23.png"),(14,))
	training_data.addSample(loadImage("n/24.png"),(14,))

	# lower case o
	training_data.addSample(loadImage("o/0.png"),(15,))
	training_data.addSample(loadImage("o/1.png"),(15,))
	training_data.addSample(loadImage("o/2.png"),(15,))
	training_data.addSample(loadImage("o/3.png"),(15,))
	training_data.addSample(loadImage("o/4.png"),(15,))
	training_data.addSample(loadImage("o/5.png"),(15,))
	training_data.addSample(loadImage("o/6.png"),(15,))
	training_data.addSample(loadImage("o/7.png"),(15,))
	training_data.addSample(loadImage("o/8.png"),(15,))
	training_data.addSample(loadImage("o/9.png"),(15,))
	training_data.addSample(loadImage("o/10.png"),(15,))
	training_data.addSample(loadImage("o/11.png"),(15,))
	training_data.addSample(loadImage("o/12.png"),(15,))
	training_data.addSample(loadImage("o/13.png"),(15,))
	training_data.addSample(loadImage("o/14.png"),(15,))
	training_data.addSample(loadImage("o/15.png"),(15,))
	training_data.addSample(loadImage("o/16.png"),(15,))
	training_data.addSample(loadImage("o/17.png"),(15,))
	training_data.addSample(loadImage("o/18.png"),(15,))
	training_data.addSample(loadImage("o/19.png"),(15,))
	training_data.addSample(loadImage("o/20.png"),(15,))
	training_data.addSample(loadImage("o/21.png"),(15,))
	training_data.addSample(loadImage("o/22.png"),(15,))
	training_data.addSample(loadImage("o/23.png"),(15,))
	training_data.addSample(loadImage("o/24.png"),(15,))
	
	# lower case p
	training_data.addSample(loadImage("p/0.png"),(16,))
	training_data.addSample(loadImage("p/1.png"),(16,))
	training_data.addSample(loadImage("p/2.png"),(16,))
	training_data.addSample(loadImage("p/3.png"),(16,))
	training_data.addSample(loadImage("p/4.png"),(16,))
	training_data.addSample(loadImage("p/5.png"),(16,))
	training_data.addSample(loadImage("p/6.png"),(16,))
	training_data.addSample(loadImage("p/7.png"),(16,))
	training_data.addSample(loadImage("p/8.png"),(16,))
	training_data.addSample(loadImage("p/9.png"),(16,))
	training_data.addSample(loadImage("p/10.png"),(16,))
	training_data.addSample(loadImage("p/11.png"),(16,))
	training_data.addSample(loadImage("p/12.png"),(16,))
	training_data.addSample(loadImage("p/13.png"),(16,))
	training_data.addSample(loadImage("p/14.png"),(16,))
	training_data.addSample(loadImage("p/15.png"),(16,))
	training_data.addSample(loadImage("p/16.png"),(16,))
	training_data.addSample(loadImage("p/17.png"),(16,))
	training_data.addSample(loadImage("p/18.png"),(16,))
	training_data.addSample(loadImage("p/19.png"),(16,))
	training_data.addSample(loadImage("p/20.png"),(16,))
	training_data.addSample(loadImage("p/21.png"),(16,))
	training_data.addSample(loadImage("p/22.png"),(16,))
	training_data.addSample(loadImage("p/23.png"),(16,))
	training_data.addSample(loadImage("p/24.png"),(16,))

	# lower case q
	training_data.addSample(loadImage("q/0.png"),(17,))
	training_data.addSample(loadImage("q/1.png"),(17,))
	training_data.addSample(loadImage("q/2.png"),(17,))
	training_data.addSample(loadImage("q/3.png"),(17,))
	training_data.addSample(loadImage("q/4.png"),(17,))
	training_data.addSample(loadImage("q/5.png"),(17,))
	training_data.addSample(loadImage("q/6.png"),(17,))
	training_data.addSample(loadImage("q/7.png"),(17,))
	training_data.addSample(loadImage("q/8.png"),(17,))
	training_data.addSample(loadImage("q/9.png"),(17,))
	training_data.addSample(loadImage("q/10.png"),(17,))
	training_data.addSample(loadImage("q/11.png"),(17,))
	training_data.addSample(loadImage("q/12.png"),(17,))
	training_data.addSample(loadImage("q/13.png"),(17,))
	training_data.addSample(loadImage("q/14.png"),(17,))
	training_data.addSample(loadImage("q/15.png"),(17,))
	training_data.addSample(loadImage("q/16.png"),(17,))
	training_data.addSample(loadImage("q/17.png"),(17,))
	training_data.addSample(loadImage("q/18.png"),(17,))
	training_data.addSample(loadImage("q/19.png"),(17,))
	training_data.addSample(loadImage("q/20.png"),(17,))
	training_data.addSample(loadImage("q/21.png"),(17,))
	training_data.addSample(loadImage("q/22.png"),(17,))
	training_data.addSample(loadImage("q/23.png"),(17,))
	training_data.addSample(loadImage("q/24.png"),(17,))

	# lower case r
	training_data.addSample(loadImage("r/0.png"),(18,))
	training_data.addSample(loadImage("r/1.png"),(18,))
	training_data.addSample(loadImage("r/2.png"),(18,))
	training_data.addSample(loadImage("r/3.png"),(18,))
	training_data.addSample(loadImage("r/4.png"),(18,))
	training_data.addSample(loadImage("r/5.png"),(18,))
	training_data.addSample(loadImage("r/6.png"),(18,))
	training_data.addSample(loadImage("r/7.png"),(18,))
	training_data.addSample(loadImage("r/8.png"),(18,))
	training_data.addSample(loadImage("r/9.png"),(18,))
	training_data.addSample(loadImage("r/10.png"),(18,))
	training_data.addSample(loadImage("r/11.png"),(18,))
	training_data.addSample(loadImage("r/12.png"),(18,))
	training_data.addSample(loadImage("r/13.png"),(18,))
	training_data.addSample(loadImage("r/14.png"),(18,))
	training_data.addSample(loadImage("r/15.png"),(18,))
	training_data.addSample(loadImage("r/16.png"),(18,))
	training_data.addSample(loadImage("r/17.png"),(18,))
	training_data.addSample(loadImage("r/18.png"),(18,))
	training_data.addSample(loadImage("r/19.png"),(18,))
	training_data.addSample(loadImage("r/20.png"),(18,))
	training_data.addSample(loadImage("r/21.png"),(18,))
	training_data.addSample(loadImage("r/22.png"),(18,))
	training_data.addSample(loadImage("r/23.png"),(18,))
	training_data.addSample(loadImage("r/24.png"),(18,))

	# lower case s
	training_data.addSample(loadImage("s/0.png"),(19,))
	training_data.addSample(loadImage("s/1.png"),(19,))
	training_data.addSample(loadImage("s/2.png"),(19,))
	training_data.addSample(loadImage("s/3.png"),(19,))
	training_data.addSample(loadImage("s/4.png"),(19,))
	training_data.addSample(loadImage("s/5.png"),(19,))
	training_data.addSample(loadImage("s/6.png"),(19,))
	training_data.addSample(loadImage("s/7.png"),(19,))
	training_data.addSample(loadImage("s/8.png"),(19,))
	training_data.addSample(loadImage("s/9.png"),(19,))
	training_data.addSample(loadImage("s/10.png"),(19,))
	training_data.addSample(loadImage("s/11.png"),(19,))
	training_data.addSample(loadImage("s/12.png"),(19,))
	training_data.addSample(loadImage("s/13.png"),(19,))
	training_data.addSample(loadImage("s/14.png"),(19,))
	training_data.addSample(loadImage("s/15.png"),(19,))
	training_data.addSample(loadImage("s/16.png"),(19,))
	training_data.addSample(loadImage("s/17.png"),(19,))
	training_data.addSample(loadImage("s/18.png"),(19,))
	training_data.addSample(loadImage("s/19.png"),(19,))
	training_data.addSample(loadImage("s/20.png"),(19,))
	training_data.addSample(loadImage("s/21.png"),(19,))
	training_data.addSample(loadImage("s/22.png"),(19,))
	training_data.addSample(loadImage("s/23.png"),(19,))
	training_data.addSample(loadImage("s/24.png"),(19,))

	# lower case t
	training_data.addSample(loadImage("t/0.png"),(20,))
	training_data.addSample(loadImage("t/1.png"),(20,))
	training_data.addSample(loadImage("t/2.png"),(20,))
	training_data.addSample(loadImage("t/3.png"),(20,))
	training_data.addSample(loadImage("t/4.png"),(20,))
	training_data.addSample(loadImage("t/5.png"),(20,))
	training_data.addSample(loadImage("t/6.png"),(20,))
	training_data.addSample(loadImage("t/7.png"),(20,))
	training_data.addSample(loadImage("t/8.png"),(20,))
	training_data.addSample(loadImage("t/9.png"),(20,))
	training_data.addSample(loadImage("t/10.png"),(20,))
	training_data.addSample(loadImage("t/11.png"),(20,))
	training_data.addSample(loadImage("t/12.png"),(20,))
	training_data.addSample(loadImage("t/13.png"),(20,))
	training_data.addSample(loadImage("t/14.png"),(20,))
	training_data.addSample(loadImage("t/15.png"),(20,))
	training_data.addSample(loadImage("t/16.png"),(20,))
	training_data.addSample(loadImage("t/17.png"),(20,))
	training_data.addSample(loadImage("t/18.png"),(20,))
	training_data.addSample(loadImage("t/19.png"),(20,))
	training_data.addSample(loadImage("t/20.png"),(20,))
	training_data.addSample(loadImage("t/21.png"),(20,))
	training_data.addSample(loadImage("t/22.png"),(20,))
	training_data.addSample(loadImage("t/23.png"),(20,))
	training_data.addSample(loadImage("t/24.png"),(20,))

	# lower case u
	training_data.addSample(loadImage("u/0.png"),(21,))
	training_data.addSample(loadImage("u/1.png"),(21,))
	training_data.addSample(loadImage("u/2.png"),(21,))
	training_data.addSample(loadImage("u/3.png"),(21,))
	training_data.addSample(loadImage("u/4.png"),(21,))
	training_data.addSample(loadImage("u/5.png"),(21,))
	training_data.addSample(loadImage("u/6.png"),(21,))
	training_data.addSample(loadImage("u/7.png"),(21,))
	training_data.addSample(loadImage("u/8.png"),(21,))
	training_data.addSample(loadImage("u/9.png"),(21,))

	# lower case v
	training_data.addSample(loadImage("v/0.png"),(22,))
	training_data.addSample(loadImage("v/1.png"),(22,))
	training_data.addSample(loadImage("v/2.png"),(22,))
	training_data.addSample(loadImage("v/3.png"),(22,))
	training_data.addSample(loadImage("v/4.png"),(22,))
	training_data.addSample(loadImage("v/5.png"),(22,))
	training_data.addSample(loadImage("v/6.png"),(22,))
	training_data.addSample(loadImage("v/7.png"),(22,))
	training_data.addSample(loadImage("v/8.png"),(22,))
	training_data.addSample(loadImage("v/9.png"),(22,))

	# lower case w
	training_data.addSample(loadImage("w/0.png"),(23,))
	training_data.addSample(loadImage("w/1.png"),(23,))
	training_data.addSample(loadImage("w/2.png"),(23,))
	training_data.addSample(loadImage("w/3.png"),(23,))
	training_data.addSample(loadImage("w/4.png"),(23,))
	training_data.addSample(loadImage("w/5.png"),(23,))
	training_data.addSample(loadImage("w/6.png"),(23,))
	training_data.addSample(loadImage("w/7.png"),(23,))
	training_data.addSample(loadImage("w/8.png"),(23,))
	training_data.addSample(loadImage("w/9.png"),(23,))

	# lower case x
	training_data.addSample(loadImage("x/0.png"),(24,))
	training_data.addSample(loadImage("x/1.png"),(24,))
	training_data.addSample(loadImage("x/2.png"),(24,))
	training_data.addSample(loadImage("x/3.png"),(24,))
	training_data.addSample(loadImage("x/4.png"),(24,))
	training_data.addSample(loadImage("x/5.png"),(24,))
	training_data.addSample(loadImage("x/6.png"),(24,))
	training_data.addSample(loadImage("x/7.png"),(24,))
	training_data.addSample(loadImage("x/8.png"),(24,))
	training_data.addSample(loadImage("x/9.png"),(24,))

	# lower case y
	training_data.addSample(loadImage("y/0.png"),(25,))
	training_data.addSample(loadImage("y/1.png"),(25,))
	training_data.addSample(loadImage("y/2.png"),(25,))
	training_data.addSample(loadImage("y/3.png"),(25,))
	training_data.addSample(loadImage("y/4.png"),(25,))
	training_data.addSample(loadImage("y/5.png"),(25,))
	training_data.addSample(loadImage("y/6.png"),(25,))
	training_data.addSample(loadImage("y/7.png"),(25,))
	training_data.addSample(loadImage("y/8.png"),(25,))
	training_data.addSample(loadImage("y/9.png"),(25,))

	# lower case z
	training_data.addSample(loadImage("z/0.png"),(26,))
	training_data.addSample(loadImage("z/1.png"),(26,))
	training_data.addSample(loadImage("z/2.png"),(26,))
	training_data.addSample(loadImage("z/3.png"),(26,))
	training_data.addSample(loadImage("z/4.png"),(26,))
	training_data.addSample(loadImage("z/5.png"),(26,))
	training_data.addSample(loadImage("z/6.png"),(26,))
	training_data.addSample(loadImage("z/7.png"),(26,))
	training_data.addSample(loadImage("z/8.png"),(26,))
	training_data.addSample(loadImage("z/9.png"),(26,))

	# train the network
	trainer = BackpropTrainer(network, training_data)
	error = 10
	iteration = 0

	
	# print the error for each training iteration, each iteration = 1 epoch
	while error > 0.001:
		error = trainer.train()
		iteration += 1
		print("Iteration: {0} Error {1}".format(iteration, error))

	# write to an xml file, comment this out when reading from one
	NetworkWriter.writeToFile(network, 'training_weights.xml')

	# read from an xml file, comment this out when training/writing
	#network = NetworkReader.readFrom('training_weights.xml')

	# print the result for a specific image query
	print("Result: ", network.activate(loadImage("a/0.png")))
	print("Result: ", network.activate(loadImage("a/1.png")))
	print("Result: ", network.activate(loadImage("a/2.png")))
	print("Result: ", network.activate(loadImage("a/3.png")))
	print("Result: ", network.activate(loadImage("a/4.png")))
	print("Result: ", network.activate(loadImage("a/5.png")))
	print("Result: ", network.activate(loadImage("a/6.png")))
	print("Result: ", network.activate(loadImage("a/7.png")))
	print("Result: ", network.activate(loadImage("a/8.png")))
	print("Result: ", network.activate(loadImage("a/9.png")))
	print("Result: ", network.activate(loadImage("a/25.png")))
	print("Result: ", network.activate(loadImage("a/26.png")))
	print("Result: ", network.activate(loadImage("a/27.png")))
	print("Result: ", network.activate(loadImage("a/28.png")))
	print("Result: ", network.activate(loadImage("a/29.png")))

	


